name: Scrum
favicon: null
layout_spectrum: 0.15108680026605725
typography_spectrum: 0.9918521295767277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.12963504064828157
  lightness: 0.38301505194976926
  saturation: 0.7215480275917798
  rhythmicContrast: 0.514091165503487
purpose: []
